# Generated by Django 2.0.9 on 2018-10-31 07:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('theme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('rank', models.CharField(default=None, max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('on_activate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_rank', models.CharField(max_length=10)),
                ('project_title', models.CharField(max_length=100)),
                ('meeting_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_web.MeetingInfo')),
                ('speaker_name', models.ForeignKey(blank=True, limit_choices_to={'on_activate': True}, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_name', to='ui_web.Members')),
            ],
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='ah_counter',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'on_activate': True}, on_delete=django.db.models.deletion.CASCADE, related_name='ah_counter', to='ui_web.Members'),
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='attendance',
            field=models.ManyToManyField(blank=True, related_name='attendance', to='ui_web.Members'),
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='best_evaluator_speaker',
            field=models.ForeignKey(blank=True, limit_choices_to={'on_activate': True}, on_delete=django.db.models.deletion.CASCADE, related_name='best_evaluator_speaker', to='ui_web.Members'),
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='best_prepared_speaker',
            field=models.ForeignKey(blank=True, limit_choices_to={'on_activate': True}, on_delete=django.db.models.deletion.CASCADE, related_name='best_prepared_speaker', to='ui_web.Members'),
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='best_table_topic_speaker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_table_topic_speaker', to='ui_web.Members'),
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='general_evaluator',
            field=models.ForeignKey(blank=True, limit_choices_to={'on_activate': True}, on_delete=django.db.models.deletion.CASCADE, related_name='general_evaluator', to='ui_web.Members'),
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='grammarian',
            field=models.ForeignKey(blank=True, limit_choices_to={'on_activate': True}, on_delete=django.db.models.deletion.CASCADE, related_name='grammarian', to='ui_web.Members'),
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='individual_evaluator',
            field=models.ManyToManyField(blank=True, limit_choices_to={'on_activate': True}, related_name='individual_evaluator', to='ui_web.Members'),
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='table_topic_master',
            field=models.ForeignKey(blank=True, limit_choices_to={'on_activate': True}, on_delete=django.db.models.deletion.CASCADE, related_name='table_topic_master', to='ui_web.Members'),
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='table_topic_speaker',
            field=models.ManyToManyField(blank=True, related_name='table_topic_speaker', to='ui_web.Members'),
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='timer',
            field=models.ForeignKey(blank=True, limit_choices_to={'on_activate': True}, on_delete=django.db.models.deletion.CASCADE, related_name='timer', to='ui_web.Members'),
        ),
        migrations.AddField(
            model_name='meetinginfo',
            name='toastmaster_of_day',
            field=models.ForeignKey(blank=True, limit_choices_to={'on_activate': True}, on_delete=django.db.models.deletion.CASCADE, related_name='toastmaster_of_day', to='ui_web.Members'),
        ),
    ]
