# Generated by Django 2.0.9 on 2018-10-23 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('count', models.CharField(max_length=10)),
                ('theme', models.CharField(max_length=100)),
                ('attendance', models.TextField()),
                ('best_table_topic_speaker', models.CharField(max_length=100)),
                ('best_prepared_speaker', models.CharField(max_length=100)),
                ('best_evaluator_speaker', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_time', models.CharField(default=django.utils.timezone.now, max_length=100)),
                ('on_activate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleTakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toastmaster_of_day', models.CharField(max_length=100)),
                ('table_topic_master', models.CharField(max_length=100)),
                ('general_evaluator', models.CharField(max_length=100)),
                ('ah_counter', models.CharField(default=None, max_length=100)),
                ('grammarian', models.CharField(default=None, max_length=100)),
                ('timer', models.CharField(default=None, max_length=100)),
                ('individual_evaluator', models.CharField(default=None, max_length=100)),
                ('meeting_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_web.MeetingInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('role_takers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_web.RoleTakers')),
            ],
        ),
    ]
