
class Config:

    NEW_DIR_TERM = "2018.10-2018.03"

    MEETING_COUNT = 108
    MEETING_THEME = "Imagine"
    MEETING_DATE = "2018.10.19"
    TableTopic = "Dongchen Tang, Taowen Zhang, Fang Yao, Jenny Yu, Shao Jing"
    BestTableTopicSpeech = "Taowen Zhang"
    BestPreparedSpeech = "Elivs Jiang"
    BestEvaluator = "Taowen Zhang"
    PREPARED_SPEAKERS = [{
        "project_rank": "CC-P8",
        "people_name": "Michelle Hua",
        "project_name": "The power of psychological hint"
    },
        {
            "project_rank": "CC-P9",
            "people_name": "Siyaun Jia",
            "project_name": "Let's learn making bread"
        },
        {
            "project_rank": "L1-4",
            "people_name": "Elvis Jiang",
            "project_name": "Deja vu"
        },
        {
            "project_rank": "",
            "people_name": "",
            "project_name": ""
        },
        {
            "project_rank": "",
            "people_name": "",
            "project_name": ""
        },
        {
            "project_rank": "",
            "people_name": "",
            "project_name": ""
        }
    ]
    ROLE_TAKERS = {
        "TMD": "Jenny Yu",
        "TTM": "Yi Fang",
        "GE": "Xin Feng",
        "IE": "Jony Zheng, Michelle Wang, Taowen Zhang",
        "Grammarian": "Dongchen Tang",
        "Timer": "Michelle Jin",
        "Ah-counter": "Huihui Jiang"
    }
    AttendanceName = "Dongchen Tang,Yi Fang,Taowen Zhang,Elvis Jiang,Jun Liu,Xin Feng,Michelle Wang,Jenny Yu,Hong Wang,Huihui Jiang,Michelle Hua, Michelle Jin, Yao Fang, Jony Zheng"

    #  you don't need to change the value.

    Message = "update {0} #{1} {2}".format(MEETING_DATE, MEETING_COUNT,
                                           MEETING_THEME)

    New_Table = """<h1>Attendance</h1>
<table class="table table-condensed table-bordered">
<tr><th>Name</th></tr>
<tr><th>eshtmc</th></tr>
<tr><th>Total</th></tr>
</table>      
    """

    md_path_dir = "eshtmc.github.io/education/meetings/{0}/".format(
        NEW_DIR_TERM)

    INDEX_ADD = """
### {0}
[attendance](https://eshtmc.github.io/education/meetings/{0}/attendance.html)
[best-awards](https://eshtmc.github.io/education/meetings/{0}/best-awards)
[role-takers](https://eshtmc.github.io/education/meetings/{0}/role-takers)
[speakers](https://eshtmc.github.io/education/meetings/{0}/speakers)
    """.format(NEW_DIR_TERM)

    HTML_ATTENDANCE_head = """
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">

<!-- Begin Jekyll SEO tag v2.5.0 -->
<title>eshtmc.github.io | database of eshtmc</title>
<meta name="generator" content="Jekyll v3.7.4" />
<meta property="og:title" content="eshtmc.github.io" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="database of eshtmc" />
<meta property="og:description" content="database of eshtmc" />
<link rel="canonical" href="https://eshtmc.github.io/education/meetings/2018.10-2018.03/attendance.html" />
<meta property="og:url" content="https://eshtmc.github.io/education/meetings/2018.10-2018.03/attendance.html" />
<meta property="og:site_name" content="eshtmc.github.io" />
<script type="application/ld+json">
{"@type":"WebPage","headline":"eshtmc.github.io","url":"https://eshtmc.github.io/education/meetings/2018.10-2018.03/attendance.html","description":"database of eshtmc","@context":"http://schema.org"}</script>
<!-- End Jekyll SEO tag -->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#157878">
    <link rel="stylesheet" href="/assets/css/style.css?v=86d9adce21742320d63342ba5413bdb59e243364">
  </head>
  <body>
    <section class="page-header">
      <h1 class="project-name">eshtmc.github.io</h1>
      <h2 class="project-tagline">database of eshtmc</h2>


    </section>

    <section class="main-content">
      <h4 id="home"><a href="https://eshtmc.github.io/">Home</a></h4>

"""

    HTML_ATTENDANCE_end = """

      <footer class="site-footer">

        <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.</span>
      </footer>
    </section>


  </body>
</html>




"""

    repository_url = "git@github.com:eshtmc/eshtmc.github.io.git"
    repository_save_path = "./eshtmc.github.io"
